### ISSUE TITLE
phonegap platform run browser error

### ISSUE THREAD

**Issue by cfjedimaster** [phonegap/phonegap-cli#481]
[phonegap] executing 'cordova platform add browser'...
Creating browser project...

Creating Browser project

Project Path platforms/browser

Package Name com.phonegap.helloworld
Project Name Hello World

TypeError: Cannot read property 'attrib' of null
    at Object.module.exports.update_from_config (/Users/ray/npm/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/cordova/metadata/browser_parser.js:52:37)
    at Object.module.exports.update_project (/Users/ray/npm/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/cordova/metadata/browser_parser.js:192:21)
    at /Users/ray/npm/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:122:27
    at Array.map (native)
    at /Users/ray/npm/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:66:40
    at _fulfilled (/Users/ray/npm/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/Users/ray/npm/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/Users/ray/npm/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:760:13)
    at /Users/ray/npm/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:574:44
    at flush (/Users/ray/npm/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:108:17)

**Comment by mwbrooks** [comment]
@cfjedimaster Some more browser support progress was made in the recent `4.2.0` update.

I'm going to close this. Feel free to re-open if you're still running into the error!

**Comment by zlatkovtv** [comment]
Removing and adding my platforms worked for me. :)
