### ISSUE TITLE
Code Sign Error on phonegap run ios

### ISSUE THREAD

**Issue by seanwash** [phonegap/phonegap-cli#498]
Hey hey,

I've googled looking for a solution to this, to no avail. When trying to run `phonegap run ios` I receive the following error:

```
[phonegap] executing 'cordova run ios'...
Running command: /Users/seanwashington/Sites/onstrategy-mobile/platforms/ios/cordova/run

Build settings from command line:

    ARCHS = armv7 armv7s arm64
    CONFIGURATION_BUILD_DIR = /Users/seanwashington/Sites/onstrategy-mobile/platforms/ios/build/device
    SDKROOT = iphoneos8.1
    VALID_ARCHS = armv7 armv7s arm64

Build settings from configuration file '/Users/seanwashington/Sites/onstrategy-mobile/platforms/ios/cordova/build.xcconfig':
    CODE_SIGN_IDENTITY = iPhone Developer


=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===



Check dependencies



=== BUILD TARGET OnStrategy Mobile OF PROJECT OnStrategy Mobile WITH CONFIGURATION Debug ===


Check dependencies

Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.

CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.1'


** BUILD FAILED **


The following build commands failed:
	Check dependencies

(1 failure)

Error: /Users/seanwashington/Sites/onstrategy-mobile/platforms/ios/cordova/run: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

[I tried following this advice as well](http://stackoverflow.com/questions/24230895/do-i-need-iphone-developer-license-to-run-cordova-phonegap-in-ios-simulator), but no dice.

Any suggestions?

**Comment by seanwash** [comment]
Hey all, fwiw I just tried `phonegap run ios --emulator` and it worked this time.

Cheers!

**Comment by mwbrooks** [comment]
@seanwash awesome!
