### ISSUE TITLE
TypeError on phonegap serve

### ISSUE THREAD

**Issue by Globegitter** [phonegap/phonegap-cli#519]
Just downloaded phonegap (On Mac OSX 10.10), created a new testapp and on running `phonegap serve` I get the following error:
```
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.handle (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/cordova/cordova.js:21:33)
    at next (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/lib/proto.js:193:15)
    at resume (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/lib/middleware/static.js:65:7)
    at SendStream.error (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/lib/middleware/static.js:80:37)
    at SendStream.emit (events.js:95:17)
    at SendStream.error (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/node_modules/send/lib/send.js:147:51)
    at SendStream.onStatError (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/node_modules/send/lib/send.js:248:48)
```

Edit: Everything seems to work fine though.

**Comment by mwbrooks** [comment]
Hi @Globegitter,

Lost track of this issue. Sorry about that. If you're still seeing the error, let's solve it!

I'll close this issue, but if you're still experiencing it, then we can reopen it.

**Comment by birender-pathania** [comment]
this is still comming

**Comment by mwbrooks** [comment]
@birender-pathania can you elaborate on your issue please?

**Comment by birender-pathania** [comment]
@mwbrooks when i run phonegap serve then it is looking for node_modules/connect-phonegap/
and giving same error

TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.handle (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/cordova/cordova.js:21:33)
    at next (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/lib/proto.js:193:15)
    at resume (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/lib/middleware/static.js:65:7)
    at SendStream.error (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/lib/middleware/static.js:80:37)
    at SendStream.emit (events.js:95:17)
    at SendStream.error (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/node_modules/send/lib/send.js:147:51)
    at SendStream.onStatError (/Users/markus/npm/lib/node_modules/phonegap/node_modules/connect-phonegap/node_modules/connect/node_modules/send/lib/send.js:248:48)

but other things working fine

**Comment by mwbrooks** [comment]
Ah, thanks @birender-pathania 

I'd like to try to recreate this issue, but it runs okay on my side. Can you answer these question when you have a moment:

1. node version? `node --version`
1. npm version? `npm --version`
1. Are you using a node version manager? e.g. nvm.
1. Is it a specific app template? Or does the happen with the Hello World?
