### ISSUE TITLE
Unable to install phonegap using node v0.10.36

### ISSUE THREAD

**Issue by askmatey** [phonegap/phonegap-cli#527]
**Environment:**

```sh
[root@batmans_cave]# uname -r
3.19.3-200.fc21.x86_64
[root@batmans_cave]# node -v
v0.10.36
[root@batmans_cave]# npm -v
1.3.6
```

**Install log (`npm-debug.log`):**

```sh
[root@batmans_cave]# npm install phonegap -g
...
npm ERR! tar.unpack untar error /root/.npm/connect-phonegap/0.15.0/package.tgz
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/phonegap/node_modules/connect-phonegap/res/middleware/cordova/3.2.0/ios/plugins/org.apache.cordova.media-capture/www/MediaFile.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.3-200.fc21.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "phonegap" "-g"
npm ERR! cwd /root
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! path /usr/lib/node_modules/phonegap/node_modules/connect-phonegap/res/middleware/cordova/3.2.0/ios/plugins/org.apache.cordova.media-capture/www/MediaFile.js
npm ERR! fstream_path /usr/lib/node_modules/phonegap/node_modules/connect-phonegap/res/middleware/cordova/3.2.0/ios/plugins/org.apache.cordova.media-capture/www/MediaFile.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! Error: unexpected eof
npm ERR!     at decorate (/usr/lib/node_modules/fstream/lib/abstract.js:67:36)
npm ERR!     at Extract.Abstract.error (/usr/lib/node_modules/fstream/lib/abstract.js:61:12)
npm ERR!     at Extract._streamEnd (/usr/lib/node_modules/tar/lib/extract.js:75:22)
npm ERR!     at BlockStream.<anonymous> (/usr/lib/node_modules/tar/lib/parse.js:50:8)
npm ERR!     at BlockStream.emit (events.js:92:17)
npm ERR!     at BlockStream._emitChunk (/usr/lib/node_modules/block-stream/block-stream.js:203:10)
npm ERR!     at BlockStream.resume (/usr/lib/node_modules/block-stream/block-stream.js:58:15)
npm ERR!     at Extract.Reader.resume (/usr/lib/node_modules/fstream/lib/reader.js:252:34)
npm ERR!     at Entry.<anonymous> (/usr/lib/node_modules/tar/lib/parse.js:256:8)
npm ERR!     at Entry.emit (events.js:92:17)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.3-200.fc21.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "phonegap" "-g"
npm ERR! cwd /root
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! fstream_class Extract
npm ERR! fstream_stack Extract._streamEnd (/usr/lib/node_modules/tar/lib/extract.js:75:22)
npm ERR! fstream_stack BlockStream.<anonymous> (/usr/lib/node_modules/tar/lib/parse.js:50:8)
npm ERR! fstream_stack BlockStream.emit (events.js:92:17)
npm ERR! fstream_stack BlockStream._emitChunk (/usr/lib/node_modules/block-stream/block-stream.js:203:10)
npm ERR! fstream_stack BlockStream.resume (/usr/lib/node_modules/block-stream/block-stream.js:58:15)
npm ERR! fstream_stack Extract.Reader.resume (/usr/lib/node_modules/fstream/lib/reader.js:252:34)
npm ERR! fstream_stack Entry.<anonymous> (/usr/lib/node_modules/tar/lib/parse.js:256:8)
npm ERR! fstream_stack Entry.emit (events.js:92:17)
...
```

**Comment by askmatey** [comment]
I was able to solve this issue with `npm cache clean`.
