### ISSUE TITLE
Couldn't find app zip to download

### ISSUE THREAD

**Issue by benno208** [phonegap/phonegap-cli#568]
When I run the ``phonegap app`` command and try to connect my mobile device, I see the following error on console:
```bash
404 /__api__/appzip
_http_outgoing.js:344
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.res.setHeader (/usr/local/lib/node_modules/phonegap/node_modules/connect/lib/patch.js:63:22)
    at ServerResponse.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect/lib/patch.js:80:14)
    at Array.forEach (native)
    at ServerResponse.res.writeHead (/usr/local/lib/node_modules/phonegap/node_modules/connect/lib/patch.js:79:28)
    at null.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:70:21)
    at emitOne (events.js:82:20)
    at emit (events.js:169:7)
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:10)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:89:29)

```

node: v5.3.0
phonegap: v5.3.9
cordova: v5.4.1

OSX El Capitan 10.11.2
Mobile Device iOS 9.2

**Comment by mwbrooks** [comment]
Thanks for submitting the issue @benno208!

@timkim this appears to be an issue with `connect-phonegap` at `connect-phonegap/lib/middleware/zip.js:70`. Any thoughts on what would be causing this?

**Comment by timkim** [comment]
Usually this is caused by an error in the zip operation. I think what's happening is that `archiver` will begin archiving files and then piping the bytes to the client. So when the server starts actually sending the bytes, the http headers are set. However, if `archiver` goes along and encounters an error, it'll throw an `archiver` error event and then tries to set a http response of `500`. But since we already set the headers previously before, the main server module doesn't like this and throws the above posted error. 

It's probably worth revisiting that error event to handle the error more gracefully. But as to what is actually causing it, it'd be worth taking a look at the project that you are trying to serve.

**Comment by benno208** [comment]
Maybe this pull request could help: 
https://github.com/phonegap/connect-phonegap/pull/127

**Comment by mwbrooks** [comment]
@benno208 Thanks for the suggestion.

I've merged the pull request it's now available on npm as:
`phonegap@5.3.10`

Give it a shot and see whether we get more info?

**Comment by benno208** [comment]
```sh
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
[phonegap] 200 /__api__/appzip
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:87:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
Error, could not complete to zip up the app:
Error: append: entry name must be a non-empty string value
    at Archiver.append (/usr/local/lib/node_modules/phonegap/node_modules/archiver/lib/core.js:317:24)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/connect-phonegap/lib/middleware/zip.js:90:29)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at fn (/usr/local/lib/node_modules/phonegap/node_modules/walkdir/walkdir.js:84:19)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by timkim** [comment]
Hrm, it really doesn't like your files for some reason. Are there any files you are trying to `serve` that have no filename? Or perhaps it's a symlink dir?

**Comment by benno208** [comment]
Yes, I have a symlink from the dist folder of my web app into www of phonegap folder... Is that a problem?

**Comment by mwbrooks** [comment]
@benno208 ah, that is the issue.

There is a pending pull request that helps resolve the issue, but it needs to be rebased and checked for issues. I'm setting aside some time tomorrow morning to try to merge it. I can loop back on this issue if everything looks good.

Pull request: https://github.com/phonegap/connect-phonegap/pull/138

**Comment by benno208** [comment]
@mwbrooks Great, thank you guys!

**Comment by mwbrooks** [comment]
@benno208 I've merged phonegap/connect-phonegap#116 to resolve the sym-link issue on OS X and Windows.

You can find the latest modules on npm as:
- `connect-phonegap@0.19.0`
- `phonegap@5.4.0`

Would you mind grabbing the latest version of PhoneGap (`phonegap@5.4.0`) and checking whether that has helped your issue?

**Comment by benno208** [comment]
So it's starts that way, but after the error it works seamlessly 
```sh
[phonegap] 404 /__api__/appzip
[phonegap] 200 /__api__/appzip
```

Thanks again

**Comment by mwbrooks** [comment]
Yea, I've noticed that as well. Odd.
