### ISSUE TITLE
Error: Upgrading to phonegap-cli 6.1.0 on Windows 10 fails and disables all functionality

### ISSUE THREAD

**Issue by chiguireitor** [phonegap/phonegap-cli#593]
After upgrading to phonegap with an administrative cmd doing `npm i -g phonegap` all the phonegap functionality gets lost.

```
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fai
l on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possibl
e.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fai
l on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possibl
e.
C:\Users\VillaPerna\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "phonegap"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path C:\Users\VillaPerna\AppData\Roaming\npm\node_modules\.staging\ansi-ce2b26a7
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\VillaPerna\AppData\Roaming\npm\node_modules\.staging\ansi-ce2b26a7' -> 'C:\Users\VillaPerna\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-lib\node_modules\ansi'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\VillaPerna\AppData\Roaming\npm\node_modules\.staging\ansi-ce2b26a7' -> 'C:\Users\VillaPerna\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-lib\node_modules\ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log
npm ERR! code 1
```

Also, when running phonegap from the cli, the following error occurs (no matter what command gets issued, even a plain `phonegap` run fails):

```
C:\Users\VillaPerna\AppData\Roaming\npm\node_modules\phonegap\node_modules\npm\l
ib\npm.js:19
  , fs = gfs.gracefulify(require('fs'))
             ^

TypeError: gfs.gracefulify is not a function
    at C:\Users\VillaPerna\AppData\Roaming\npm\node_modules\phonegap\node_modules\npm\lib\npm.js:19:14
    at Object.<anonymous> (C:\Users\VillaPerna\AppData\Roaming\npm\node_modules\phonegap\node_modules\npm\lib\npm.js:475:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\VillaPerna\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-lib\src\cordova\util.js:27:21)
    at Module._compile (module.js:413:34)
```

[npm-debug.txt](https://github.com/phonegap/phonegap-cli/files/227745/npm-debug.txt)

**Comment by surajpindoria** [comment]
Hi @chiguireitor,

Someone was having a similar issue with this last week as well, #591. They were able to solve this issue by first uninstalling the CLI, `npm uninstall -g phonegap`, and then re-installing. Can you try this and let me know if it works?

**Comment by chiguireitor** [comment]
Yeap... that solved it. Thanks
