### ISSUE TITLE
phonegap --push gives SyntaxError

### ISSUE THREAD

**Issue by ieyring** [phonegap/phonegap-cli#607]
phonegap push --deviceID [XXX-HERE-THE-DEVICE-ID-XXX] --service gcm --payload '{ "data": { "title": "Hello", "message": "World"} }' failes wih an SyntaxError:

undefined:1
'{data:{
^

SyntaxError: Unexpected token '
    at Object.parse (native)
    at PushCommand.execute (C:\Users\User\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\push.js:76:23)
    at PushCommand.run (C:\Users\User\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\push.js:54:8)
    at PhoneGap.push (C:\Users\User\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\util\command.js:28:25)
    at CLI.module.exports [as push] (C:\Users\User\AppData\Roaming\npm\node_modules\phonegap\lib\cli\push.js:27:12)
    at CLI.module.exports [as argv] (C:\Users\User\AppData\Roaming\npm\node_modules\phonegap\lib\cli\argv.js:116:17)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js:13:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

Something seems wrong with the payload, but i can't figure it out.

OS: Win10

**Comment by macdonst** [comment]
@ieyring yeah, you need to use the Windows syntax which I will improve the help docs.

On Windows:

`phonegap push --deviceID [XXX-HERE-THE-DEVICE-ID-XXX] --service gcm --payload "{ \"data\":{ \"title\": \"Hello\", \"message\": \"World\"} }"`

**Comment by macdonst** [comment]
I pushed a doc fix to master to take care of this and it will be in the next release. Closing the issue for now as you can use the syntax in the previous comment to do a push.

**Comment by OutsourcedGuru** [comment]
@macdonst Actually, the working syntax for the PhoneGap-generated Push Notification demo code was:  
```
phonegap push --deviceID [XXX-HERE-THE-DEVICE-ID-XXX] --service apns --payload "{ \"aps\":{ \"alert\": \"Hello World\"} }"
```
Any other attempt wouldn't trigger the app to actually pass it through.

**Comment by macdonst** [comment]
@OutsourcedGuru Yeah you use apns for Apple and gcm for Android.

**Comment by OutsourcedGuru** [comment]
@macdonst Thanks.  It was disappointing going through that demo only to have it fail.  Perhaps someone can update the demo page for that.  (At least I now know how to make this work.)
