### ISSUE TITLE
Error: category and action required ...

### ISSUE THREAD

**Issue by klarizonemar** [phonegap/phonegap-cli#609]
I have problem running the `phonegap` command

Here's the output. The error shows at the end.

How can I fix this? Thank you.

```
Usage: phonegap [options] [commands]

Description:

  PhoneGap command-line tool.

Commands:

  help [command]       output usage information
  create <path>        create a phonegap project
  build <platforms>    build the project for a specific platform
  install <platforms>  install the project on for a specific platform
  run <platforms>      build and install the project for a specific platform
  platform [command]   update a platform version
  plugin [command]     add, remove, and list plugins
  template [command]   list available app templates
  info                 display information about the project
  serve                serve a phonegap project
  version              output version number
  push                 send test push notification
  analytics            turn analytics on or off, or view current status

Additional Commands:

  local [command]      development on local system
  remote [command]     development in cloud with phonegap/build
  prepare <platforms>  copies www/ into platform project before compiling
  compile <platforms>  compiles platform project without preparing it
  emulate <platforms>  runs the project with the flag --emulator
  cordova              execute of any cordova command

Options:

  -d, --verbose        allow verbose output
  -v, --version        output version number
  -h, --help           output usage information
  --no-update-notifier disable update notifier, to opt-out of update-notifier
                       change the 'optOut' property to 'true' in
                       ~/.config/configstore/update-notifier-phonegap.yml

Examples:

  $ phonegap help create
  $ phonegap create path/to/my-app
  $ cd my-app/
  $ phonegap run ios
  $ phonegap analytics on

/usr/lib/node_modules/phonegap/node_modules/insight/lib/index.js:114
		throw new Error('category and action required');
		^

Error: category and action required
    at Insight.trackEvent (/usr/lib/node_modules/phonegap/node_modules/insight/lib/index.js:114:9)
    at Function.trackEvent (/usr/lib/node_modules/phonegap/lib/cli/analytics.js:135:17)
    at /usr/lib/node_modules/phonegap/bin/phonegap.js:39:19
    at CLI.module.exports [as help] (/usr/lib/node_modules/phonegap/lib/cli/help.js:48:5)
    at CLI.module.exports [as argv] (/usr/lib/node_modules/phonegap/lib/cli/argv.js:116:17)
    at runPhoneGapCommand (/usr/lib/node_modules/phonegap/bin/phonegap.js:31:9)
    at Object.<anonymous> (/usr/lib/node_modules/phonegap/bin/phonegap.js:23:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

**Comment by surajpindoria** [comment]
Hi @klarizonemar,

Thank you for pointing this out! This error is not an issue with PhoneGap but with the module we use for analytics. All other PhoneGap commands should work as expected.

**Comment by purplecabbage** [comment]
This is a phonegap error. My mistake.
Currently the basic commands `phonegap help`, `phonegap -h` and `phonegap --help` will fail.
The patch will be out soon.
As a temporary workaround you can use `phonegap help -h`

**Comment by klarizonemar** [comment]
Ok. Thank you guys!
