### ISSUE TITLE
Regression of remote build through phonegap-cli in 6.3.0

### ISSUE THREAD

**Issue by ironfroggy** [phonegap/phonegap-cli#633]
Using Node 4.2.4, upgrading to phonegap-cli 6.3.0 broke remote builds. Fixed by downgrading to 6.2.9.

This issue was also raised on the Phonegap Build forums: https://forums.adobe.com/thread/2185419

```
[phonegap] compressing the app...
[phonegap] uploading the app...
_http_client.js:51
    throw new TypeError('Request path contains unescaped characters.');
    ^

TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:51:11)
    at Object.exports.request (http.js:31:10)
    at TunnelingAgent.exports.request (https.js:163:15)
    at TunnelingAgent.createSocket (/Users/calvin/projects/edxpassapp/node_modules/phonegap-build-api/node_modules/request/tunnel.js:116:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/Users/calvin/projects/edxpassapp/node_modules/phonegap-build-api/node_modules/request/tunnel.js:188:41)
    at TunnelingAgent.addRequest (/Users/calvin/projects/edxpassapp/node_modules/phonegap-build-api/node_modules/request/tunnel.js:80:8)
    at new ClientRequest (_http_client.js:133:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:163:15)
    at Request.start (/Users/calvin/projects/edxpassapp/node_modules/phonegap-build-api/node_modules/request/main.js:516:30)
```

**Comment by surajpindoria** [comment]
If you haven't already, can one of you please take a look at this?

@wildabeast @goya

**Comment by mwbrooks** [comment]
@surajpindoria this may be an issue in https://github.com/phonegap/node-phonegap-build and not directly the PGB API.

**Comment by surajpindoria** [comment]
Ok, I'll take a look into this further too

**Comment by mwbrooks** [comment]
@surajpindoria ping me if you'd like to walk through how the PG CLI uses the `node-phonegap-build` module. It's pretty straight-forward though.
