### ISSUE TITLE
Do not add android platform in phonegap

### ISSUE THREAD

**Issue by jailupatel007** [phonegap/phonegap-cli#676]
C:\Jay\Demo>phonegap platform add android
Warning: using node version v0.10.28 which has been deprecated. Please upgrade t
o the latest node version available (v6.x is recommended).

Adding android project...

Running command: cmd "/s /c ""C:\Documents and Settings\Administrator\.cordova\l
ib\npm_cache\cordova-android\6.0.0\package\bin\create.bat" C:\Jay\Demo\platforms
\android com.example.administrator.demo Demo --cli""

C:\Documents and Settings\Administrator\.cordova\lib\npm_cache\cordova-android\6
.0.0\package\bin\templates\cordova\lib\AndroidStudio.js:16
    for(file of eclipseFiles) {
             ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Documents and Settings\Administrator\.cordova\lib\
npm_cache\cordova-android\6.0.0\package\bin\templates\cordova\lib\AndroidProject
.js:24:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

C:\Documents and Settings\Administrator\.cordova\lib\npm_cache\cordova-android\6
.0.0\package\bin\templates\cordova\lib\AndroidStudio.js:16
    for(file of eclipseFiles) {
             ^^

What I can next  Step to solve this error ?

**Comment by surajpindoria** [comment]
Hi @jailupatel007,

The version of node you are using does not work with the PhoneGap CLI. You should upgrade to a version that is 4.0.0 or greater.

**Comment by filmaj** [comment]
Closing due to unsupported node version.
