### ISSUE TITLE
`SyntaxError: Unexpected token >` in node 0.10.48

### ISSUE THREAD

**Issue by brad** [phonegap/phonegap-cli#683]
I'm seeing a syntax error when trying to do anything with phonegap 6.4.3 on node 0.10.48. Phonegap 6.4.2 works fine.

### PhoneGap CLI, node & npm versions
PhoneGap 6.4.3
node 0.10.48
npm 2.15.1

### Expected Behaviour
Functionality

### Actual Behaviour
Immediate syntax error with any command

### Steps to Reproduce 
1. Run `phonegap --version`
2. See syntax error

#### Sample Code that illustrates the problem
`phonegap --version`

#### Error messages
```
/usr/lib/node_modules/phonegap/lib/phonegap/util/connect-proxy.js:21
                fs.readFile(settings, (err, data) => {
                                                   ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/phonegap/lib/phonegap/serve.js:9:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by surajpindoria** [comment]
Hey @brad,

The version of node you are using does not support ES6 features, which is why you are seeing this error. If you update your node version to 4.0.0+ you should be able to use the CLI.

**Comment by brad** [comment]
@surajpindoria Oh, so phonegap no longer supports 0.10.x? In that case the README needs an update to reflect that.

**Comment by surajpindoria** [comment]
Yes, thanks for pointing out the discrepancy in the README. I updated the minimum node version awhile back and forgot to change it in the docs. @brad

**Comment by surajpindoria** [comment]
Hi @skysim,

You need to update the version of node you have installed on your system. The minimum required for the `phonegap-cli` is 4.0.0. This version includes support for ES6 syntax which is causing the above issue for you.

**Comment by skysim** [comment]
Thanks for replying, but there is some connections problem in LINUX such as the address i get from the LINUX cant connect to the App in phone 192.168.125.129:3000 which is a private address that cant be connected. Is there any solutions for it?

**Comment by surajpindoria** [comment]
Take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), there are a bunch of suggestions that mayork settings to allow peer-to-peer connections.to modify your network settings to allow peer-to-peer connections.

**Comment by vinitpatel03** [comment]
i have same problem
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Node js version : v8.11.3

**Comment by NRNProjects** [comment]
I have the same issue. Tried to remove npm as suggested, but did not work.

/usr/local/lib/node_modules/@angular/cli/bin/ng:17
var version = process.versions.node.split('.').map(part => Number(part));
                                                         ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Node version : v0.10.28
