### ISSUE TITLE
Unable to run phonegap serve from cli

### ISSUE THREAD

**Issue by aqeelcodeenterprises** [phonegap/phonegap-cli#735]
Everything was working fine before but now after restarting laptop when I run this command to start and serve my `PhoneGap` application in the browser with the following command from `CLI`

            `phonegap serve `
or

            `phonegap serve --browser`
It gives me following error:

> There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
> Error: watch /var/www/html/test/react/phonegap/myapp/www/app/ ENOSPC
>     at exports._errnoException (util.js:1024:11)
>     at FSWatcher.start (fs.js:1382:19)
>     at Object.fs.watch (fs.js:1408:11)
>     at Gaze._watchDir (/usr/local/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:304:30)
>     at /usr/local/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:377:10
>     at iterate (/usr/local/lib/node_modules/phonegap/node_modules/gaze/lib/helper.js:69:5)
>     at Object.forEachSeries (/usr/local/lib/node_modules/phonegap/node_modules/gaze/lib/helper.js:83:3)
>     at Gaze._initWatched (/usr/local/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:373:10)
>     at Gaze.add (/usr/local/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:192:8)
>     at new Gaze (/usr/local/lib/node_modules/phonegap/node_modules/gaze/lib/gaze.js:74:10)

How I can get ride out of this problem...
Any help will be appreciated, Thanks...

**Comment by aqeelcodeenterprises** [comment]
Hi,

It solved using `sudo` as:

         sudo phonegap serve --browser

Thanks for looking into it. :+1:

**Comment by surajpindoria** [comment]
Hi @aqeelcodeenterprises,

Glad you got this to work! I think there might be something else going on though as this is the second report with the same npm error, ENOSPC. Looks to be an issue with the `gaze` module we use to watch for file changes to your project. Will continue looking into this.

**Comment by aqeelcodeenterprises** [comment]
Hi @surajpindoria 

Thanks, bro.

**Comment by BHunter2889** [comment]
Any Updates on a resolution to this? I'm hoping to be able to publicly serve an app prototype for a demo this Friday and I'm getting this exact stacktrace even with sudo unfortunately. I'll continue debugging and let you know what I find out if I don't hear back first.

**Comment by tamb** [comment]
> 
> 
> Hi @aqeelcodeenterprises,
> 
> Glad you got this to work! I think there might be something else going on though as this is the second report with the same npm error, ENOSPC. Looks to be an issue with the `gaze` module we use to watch for file changes to your project. Will continue looking into this.

I think that `gaze` is watching all of `node_modules` if you happen to have that directory within the `www` directory.  Is there a way to ignore certain files/directories from `gaze` / `phonegap serve` ??
