### ISSUE TITLE
Don't understand phonegap-cli behaviour with templates & errors

### ISSUE THREAD

**Issue by juanda99** [phonegap/phonegap-cli#736]
### Versions

Just installed virtual machine with Windows 8.1 to test phonegap
My versions:

```
C:\Users\JuanDaniel\Desktop\cordova1>node --version
v6.11.2

C:\Users\JuanDaniel\Desktop\cordova1>git --version
git version 2.14.1.windows.1

C:\Users\JuanDaniel\Desktop\cordova1>phonegap --version
7.0.0
```

### Expected Behaviour
Phonegap serve without erros
### Actual Behaviour
Errors firt time run , no next times. 

### Steps to Reproduce 
I just create sample project:

```
C:\Users\JuanDaniel\Desktop>phonegap create project1
Creating a new cordova project.
```
When I try to run it I got errors installing plugins:

```
C:\Users\JuanDaniel\Desktop>cd project1
C:\Users\JuanDaniel\Desktop\project1>phonegap serve
[phonegap] starting app server...
[phonegap] listening on 172.16.205.168:3000
[phonegap]
[phonegap] ctrl-c to stop the server
[phonegap]
Using cordova-fetch for cordova-browser@~4.1.0


Adding browser project...

Running command: cmd "/s /c "C:\Users\JuanDaniel\Desktop\project1\node_modules\cordova-browser\bin\create.bat C:\Users\JuanDaniel\Desktop\project1\platforms\browser com.phonegap.he
lloworld helloworld""

Creating Browser project. Path: platforms\browser

Discovered plugin "cordova-plugin-battery-status" in config.xml. Adding it to the project

Installing "cordova-plugin-battery-status" for browser


Saved plugin info for "cordova-plugin-battery-status" to config.xml


Discovered plugin "cordova-plugin-camera" in config.xml. Adding it to the project

Installing "cordova-plugin-camera" for browser


Saved plugin info for "cordova-plugin-camera" to config.xml


Discovered plugin "cordova-plugin-media-capture" in config.xml. Adding it to the project


Installing "cordova-plugin-media-capture" for browser

Failed to install 'cordova-plugin-media-capture': CordovaError: Failed to fetch plugin cordova-plugin-file@^4.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN cordova-plugin-media-capture@1.2.0 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN project1 No description
npm WARN project1 No repository field.
npm WARN project1 No README data
npm WARN project1 No license field.
npm ERR! code 1
    at C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-lib\src\plugman\fetch.js:205:33
    at _rejected (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:864:24)
    at C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:808:41)
    at C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:624:44
    at runSingle (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:137:13)
    at flush (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Failed to restore plugin "cordova-plugin-media-capture" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-file@^4.0.0 via registr
y.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN cordova-plugin-media-capture@1.2.0 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN project1 No description
npm WARN project1 No repository field.
npm WARN project1 No README data
npm WARN project1 No license field.
npm ERR! code 1
Discovered plugin "cordova-plugin-console" in config.xml. Adding it to the project

Installing "cordova-plugin-console" for browser


Saved plugin info for "cordova-plugin-console" to config.xml


Discovered plugin "cordova-plugin-contacts" in config.xml. Adding it to the project


Installing "cordova-plugin-contacts" for browser


Saved plugin info for "cordova-plugin-contacts" to config.xml


Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project


Installing "cordova-plugin-device" for browser

Saved plugin info for "cordova-plugin-device" to config.xml


Discovered plugin "cordova-plugin-device-motion" in config.xml. Adding it to the project

Installing "cordova-plugin-device-motion" for browser


Saved plugin info for "cordova-plugin-device-motion" to config.xml


Discovered plugin "cordova-plugin-device-orientation" in config.xml. Adding it to the project

Installing "cordova-plugin-device-orientation" for browser


Saved plugin info for "cordova-plugin-device-orientation" to config.xml


Discovered plugin "cordova-plugin-dialogs" in config.xml. Adding it to the project


Installing "cordova-plugin-dialogs" for browser


Saved plugin info for "cordova-plugin-dialogs" to config.xml


Discovered plugin "cordova-plugin-file" in config.xml. Adding it to the project


Failed to restore plugin "cordova-plugin-file" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-file@~4.1.1 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN cordova-plugin-media-capture@1.2.0 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN project1 No description
npm WARN project1 No repository field.
npm WARN project1 No README data
npm WARN project1 No license field.
npm ERR! code 1

Discovered plugin "cordova-plugin-file-transfer" in config.xml. Adding it to the project

Installing "cordova-plugin-file-transfer" for browser

Failed to install 'cordova-plugin-file-transfer': CordovaError: Failed to fetch plugin cordova-plugin-file@^4.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN cordova-plugin-file-transfer@1.5.1 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN cordova-plugin-media-capture@1.2.0 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN project1 No description
npm WARN project1 No repository field.
npm WARN project1 No README data
npm WARN project1 No license field.
npm ERR! code 1
    at C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-lib\src\plugman\fetch.js:205:33
    at _rejected (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:864:24)
    at C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:808:41)
    at C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:624:44
    at runSingle (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:137:13)
    at flush (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Failed to restore plugin "cordova-plugin-file-transfer" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-file@^4.0.0 via registr
y.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN cordova-plugin-file-transfer@1.5.1 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN cordova-plugin-media-capture@1.2.0 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN project1 No description
npm WARN project1 No repository field.
npm WARN project1 No README data
npm WARN project1 No license field.
npm ERR! code 1
Discovered plugin "cordova-plugin-geolocation" in config.xml. Adding it to the project

Installing "cordova-plugin-geolocation" for browser

Saved plugin info for "cordova-plugin-geolocation" to config.xml


Discovered plugin "cordova-plugin-globalization" in config.xml. Adding it to the project

Installing "cordova-plugin-globalization" for browser


Saved plugin info for "cordova-plugin-globalization" to config.xml


Discovered plugin "cordova-plugin-inappbrowser" in config.xml. Adding it to the project


Installing "cordova-plugin-inappbrowser" for browser


Saved plugin info for "cordova-plugin-inappbrowser" to config.xml


Discovered plugin "cordova-plugin-media" in config.xml. Adding it to the project

Installing "cordova-plugin-media" for browser

Failed to install 'cordova-plugin-media': CordovaError: Failed to fetch plugin cordova-plugin-file@^4.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN cordova-plugin-file-transfer@1.5.1 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN cordova-plugin-media-capture@1.2.0 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN project1 No description
npm WARN project1 No repository field.
npm WARN project1 No README data
npm WARN project1 No license field.
npm ERR! code 1
    at C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-lib\src\plugman\fetch.js:205:33
    at _rejected (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:864:24)
    at C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:808:41)
    at C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:624:44
    at runSingle (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:137:13)
    at flush (C:\Users\JuanDaniel\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-fetch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Failed to restore plugin "cordova-plugin-media" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-plugin-file@^4.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\JuanDaniel\Desktop\project1\package.json'
npm WARN cordova-plugin-file-transfer@1.5.1 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN cordova-plugin-media-capture@1.2.0 requires a peer of cordova-plugin-file@^3.0.0 but none was installed.
npm WARN project1 No description
npm WARN project1 No repository field.
npm WARN project1 No README data
npm WARN project1 No license field.
npm ERR! code 1
Discovered plugin "cordova-plugin-network-information" in config.xml. Adding it to the project

Installing "cordova-plugin-network-information" for browser

Saved plugin info for "cordova-plugin-network-information" to config.xml


Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project


Installing "cordova-plugin-splashscreen" for browser


Saved plugin info for "cordova-plugin-splashscreen" to config.xml


Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project


Installing "cordova-plugin-statusbar" for browser


Saved plugin info for "cordova-plugin-statusbar" to config.xml


Discovered plugin "cordova-plugin-vibration" in config.xml. Adding it to the project


Installing "cordova-plugin-vibration" for browser

Saved plugin info for "cordova-plugin-vibration" to config.xml


Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project

Installing "cordova-plugin-whitelist" for browser


Saved plugin info for "cordova-plugin-whitelist" to config.xml


--save flag or autosave detected

Saving browser@~4.1.0 into config.xml file ...




```

However it works. I go to localhost:3000 and I have "Device is ready" message. Shouldn't it be hang on "Connecting to device"? As no device is present or even plattform yet installed.

Next times console is ok, see logs:
```

C:\Users\JuanDaniel\Desktop\project1>
C:\Users\JuanDaniel\Desktop\project1>phonegap serve
[phonegap] starting app server...
[phonegap] listening on 172.16.205.168:3000
[phonegap]
[phonegap] ctrl-c to stop the server
[phonegap]
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=LuppREl
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=LuppRU3&sid=uz_UTR6swpzh3RHMAAAA
[phonegap] 200 /
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=LuppRUG&sid=uz_UTR6swpzh3RHMAAAA
[phonegap] 200 /css/index.css
[phonegap] 200 /cordova.js
[phonegap] 200 /js/index.js
[phonegap] 304 /socket.io/socket.io.js
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=LuppRX4
[phonegap] 200 /img/logo.png
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=LuppRXL&sid=fkcFkL2c6cTJcSEuAAAB
[phonegap] 200 /cordova_plugins.js
[phonegap] 200 /plugins/cordova-plugin-battery-status/www/battery.js
[phonegap] 200 /plugins/cordova-plugin-battery-status/src/browser/BatteryProxy.js
[phonegap] 200 /plugins/cordova-plugin-camera/www/CameraConstants.js
[phonegap] 200 /plugins/cordova-plugin-camera/www/CameraPopoverOptions.js
[phonegap] 200 /plugins/cordova-plugin-camera/src/browser/CameraProxy.js
[phonegap] 200 /plugins/cordova-plugin-camera/www/Camera.js
[phonegap] 200 /plugins/cordova-plugin-contacts/www/contacts.js
[phonegap] 200 /plugins/cordova-plugin-contacts/www/Contact.js
[phonegap] 200 /plugins/cordova-plugin-contacts/www/ContactAddress.js
[phonegap] 200 /plugins/cordova-plugin-contacts/www/ContactError.js
[phonegap] 200 /plugins/cordova-plugin-contacts/www/ContactField.js
[phonegap] 200 /plugins/cordova-plugin-contacts/www/ContactFindOptions.js
[phonegap] 200 /plugins/cordova-plugin-contacts/www/ContactName.js
[phonegap] 200 /plugins/cordova-plugin-contacts/www/ContactOrganization.js
[phonegap] 200 /plugins/cordova-plugin-contacts/www/ContactFieldType.js
[phonegap] 200 /plugins/cordova-plugin-device/www/device.js
[phonegap] 200 /plugins/cordova-plugin-device/src/browser/DeviceProxy.js
[phonegap] 200 /plugins/cordova-plugin-device-motion/www/Acceleration.js
[phonegap] 200 /plugins/cordova-plugin-device-motion/www/accelerometer.js
[phonegap] 200 /plugins/cordova-plugin-device-motion/src/browser/AccelerometerProxy.js
[phonegap] 200 /plugins/cordova-plugin-device-orientation/www/CompassError.js
[phonegap] 200 /plugins/cordova-plugin-device-orientation/www/CompassHeading.js
[phonegap] 200 /plugins/cordova-plugin-device-orientation/www/compass.js
[phonegap] 200 /plugins/cordova-plugin-device-orientation/src/browser/CompassProxy.js
[phonegap] 200 /plugins/cordova-plugin-dialogs/www/notification.js
[phonegap] 200 /plugins/cordova-plugin-dialogs/www/browser/notification.js
[phonegap] 200 /plugins/cordova-plugin-globalization/www/GlobalizationError.js
[phonegap] 200 /plugins/cordova-plugin-globalization/www/globalization.js
[phonegap] 200 /plugins/cordova-plugin-globalization/src/browser/GlobalizationProxy.js
[phonegap] 200 /plugins/cordova-plugin-inappbrowser/www/inappbrowser.js
[phonegap] 200 /plugins/cordova-plugin-inappbrowser/src/browser/InAppBrowserProxy.js
[phonegap] 200 /plugins/cordova-plugin-network-information/www/network.js
[phonegap] 200 /plugins/cordova-plugin-network-information/www/Connection.js
[phonegap] 200 /plugins/cordova-plugin-network-information/src/browser/network.js
[phonegap] 200 /plugins/cordova-plugin-splashscreen/www/splashscreen.js
[phonegap] 200 /plugins/cordova-plugin-globalization/www/browser/moment.js
[phonegap] 200 /plugins/cordova-plugin-splashscreen/src/browser/SplashScreenProxy.js
[phonegap] 200 /plugins/cordova-plugin-statusbar/www/statusbar.js
[phonegap] 200 /plugins/cordova-plugin-statusbar/src/browser/statusbar.js
[phonegap] 200 /plugins/cordova-plugin-vibration/src/browser/Vibration.js
[phonegap] 200 /plugins/cordova-plugin-vibration/www/vibration.js
[phonegap] 200 /plugins/cordova-plugin-file/www/DirectoryEntry.js
[phonegap] 200 /plugins/cordova-plugin-file/www/DirectoryReader.js
[phonegap] 200 /plugins/cordova-plugin-file/www/Entry.js
[phonegap] 200 /plugins/cordova-plugin-file/www/File.js
[phonegap] 200 /plugins/cordova-plugin-file/www/FileEntry.js
[phonegap] 200 /plugins/cordova-plugin-file/www/FileError.js
[phonegap] 200 /plugins/cordova-plugin-file/www/FileReader.js
[phonegap] 200 /plugins/cordova-plugin-file/www/FileSystem.js
[phonegap] 200 /plugins/cordova-plugin-file/www/FileUploadOptions.js
[phonegap] 200 /plugins/cordova-plugin-file/www/FileUploadResult.js
[phonegap] 200 /plugins/cordova-plugin-file/www/FileWriter.js
[phonegap] 200 /plugins/cordova-plugin-file/www/Flags.js
[phonegap] 200 /plugins/cordova-plugin-file/www/LocalFileSystem.js
[phonegap] 200 /plugins/cordova-plugin-file/www/Metadata.js
[phonegap] 200 /plugins/cordova-plugin-file/www/ProgressEvent.js
[phonegap] 200 /plugins/cordova-plugin-file/www/fileSystems.js
[phonegap] 200 /plugins/cordova-plugin-file/www/requestFileSystem.js
[phonegap] 200 /plugins/cordova-plugin-file/www/resolveLocalFileSystemURI.js
[phonegap] 200 /plugins/cordova-plugin-file/www/browser/isChrome.js
[phonegap] 200 /plugins/cordova-plugin-file/www/browser/Preparing.js
[phonegap] 200 /plugins/cordova-plugin-file/src/browser/FileProxy.js
[phonegap] 200 /plugins/cordova-plugin-file/www/fileSystemPaths.js
[phonegap] 200 /plugins/cordova-plugin-file/www/browser/FileSystem.js
[phonegap] [console.log] adding proxy for Battery
[phonegap] 200 /config.xml
[phonegap] 200 /img/logo.png
[phonegap] [console.log] adding proxy for Camera
[phonegap] [console.log] adding proxy for Device
[phonegap] [console.log] adding proxy for Accelerometer
[phonegap] [console.log] adding proxy for Compass
[phonegap] [console.log] adding proxy for Globalization
[phonegap] [console.log] adding proxy for InAppBrowser
[phonegap] [console.log] adding proxy for NetworkStatus
[phonegap] [console.log] adding proxy for SplashScreen
[phonegap] [console.log] adding proxy for File
[phonegap] [console.log] Persistent fs quota granted
[phonegap] [console.log] Error: exec proxy not found for :: StatusBar :: _ready
[phonegap] [console.log] Received Event: deviceready
```

**Comment by juanda99** [comment]
Upps, i see https://phonegap.com/blog/2016/02/19/browser/ and now i understand the device ready event. What about the erros?

**Comment by surajpindoria** [comment]
Hi @juanda99,

Those errors are related to an issue in npm and the some of our plugins. You should be able to fix them by updating to the latest npm, `npm install -g npm`. Once you have done that on the next run of `phonegap serve` it should be able to add those plugins that were failing before.

**Comment by juanda99** [comment]
Ummm thank you!
Just did something similar with Linux before without problems.. and I was thinking it was related to Windows and plugins incompatibilities through CLI.
