### ISSUE TITLE
push notification

### ISSUE THREAD

**Issue by mohamedgb00714** [phonegap/phonegap-cli#742]
There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
Error: requires payload parameter
    at PushCommand.execute (C:\Users\mohamedgb\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\push.js:65:33)
    at PushCommand.run (C:\Users\mohamedgb\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\push.js:51:10)
    at PhoneGap.push (C:\Users\mohamedgb\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\util\command.js:28:25)
    at CLI.module.exports [as push] (C:\Users\mohamedgb\AppData\Roaming\npm\node_modules\phonegap\lib\cli\push.js:27:14)
    at CLI.module.exports [as argv] (C:\Users\mohamedgb\AppData\Roaming\npm\node_modules\phonegap\lib\cli\argv.js:113:17)
    at runPhoneGapCommand (C:\Users\mohamedgb\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js:48:9)
    at Object.<anonymous> (C:\Users\mohamedgb\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js:40:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

**Comment by purplecabbage** [comment]
Push notifications are no longer supported within the cli.  The dev push service has been shut down.
Details and some alternatives here: https://blog.phonegap.com/discontinuing-the-phonegap-push-service-540251bfc98
Sorry for any inconvenience.
