### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by mushishi78** [phonegap/phonegap-cli#751]
https://github.com/phonegap/phonegap-cli/blob/4b0b681735679c6438c991227cb94d9c5b82021e/lib/phonegap/serve.js#L100

This clearly returns nothing and 

https://github.com/phonegap/phonegap-cli/blob/4b0b681735679c6438c991227cb94d9c5b82021e/lib/phonegap/serve.js#L87

Expects a promise.

**Comment by lsolesen** [comment]
Did you ever get this working. I have this problem on AWS Cloud9 when developing

```
$ phonegap serve -b 0.0.0.0 -p 8080
   [error] project directory could not be found
There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
TypeError: Cannot read property 'then' of undefined
    at AppCommand.run (/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/phonegap/lib/phonegap/serve.js:87:43)
    at PhoneGap.<anonymous> (/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/phonegap/lib/phonegap/util/command.js:28:25)
    at CLI.module.exports (/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/phonegap/lib/cli/serve.js:36:14)
    at CLI.module.exports [as argv] (/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/phonegap/lib/cli/argv.js:111:17)
    at runPhoneGapCommand (/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/phonegap/bin/phonegap.js:46:9)
    at Object.<anonymous> (/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/phonegap/bin/phonegap.js:38:5)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
```

**Comment by mushishi78** [comment]
I was just pointing out that this was bad code. It's meant to just say "[error] project directory could not be found" and then exit with a failure status.

Instead it fails to return a promise, so it creates an unhandled exception afterwards which is just noise. Not a big issue, but I thought I'd point it out as it makes a confusing message.

Your problem is just that the it can't find a cordova (phonegap) project from the directory it's being run in. It starts in the current working directory and then continues up the file system. It ships out to the 'cordova' package to run the actual check of what it considers to be a cordova project. I'd guess that it looks for a 'config.xml' file, but I haven't looked that up or anything.

**Comment by Uzgraph** [comment]
The same situation, I think the problem is in the installation defect related with that npm had no permission to write data into the specified folders. 
Open the specified "lib" folder. Does it contains the specified folder "node_modules"?
In my case it is not.

**Comment by Uzgraph** [comment]
"you should run your commands from your actual project folder. Common mistake is that people try out of the project folder. use "cd folder" and try. – Purus Nov 25 '13 at 18:55"
https://stackoverflow.com/questions/20197542/where-phonegap-defines-project-directory
So:
cd myApp
phonegap serve
