### ISSUE TITLE
when run (Push Notifications) on CLI  SyntaxError appear

### ISSUE THREAD

**Issue by Bothina88** [phonegap/phonegap-cli#752]
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at PushCommand.execute (C:\Users\Bothinahamed\AppData\Roaming\npm\node_modul
es\phonegap\lib\phonegap\push.js:71:23)
    at PushCommand.run (C:\Users\Bothinahamed\AppData\Roaming\npm\node_modules\p
honegap\lib\phonegap\push.js:51:10)
    at PhoneGap.push (C:\Users\Bothinahamed\AppData\Roaming\npm\node_modules\pho
negap\lib\phonegap\util\command.js:28:25)
    at CLI.module.exports [as push] (C:\Users\Bothinahamed\AppData\Roaming\npm\n
ode_modules\phonegap\lib\cli\push.js:27:14)
    at CLI.module.exports [as argv] (C:\Users\Bothinahamed\AppData\Roaming\npm\n
ode_modules\phonegap\lib\cli\argv.js:113:17)
    at runPhoneGapCommand (C:\Users\Bothinahamed\AppData\Roaming\npm\node_module
s\phonegap\bin\phonegap.js:48:9)
    at Object.<anonymous> (C:\Users\Bothinahamed\AppData\Roaming\npm\node_module
s\phonegap\bin\phonegap.js:40:5)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)

**Comment by surajpindoria** [comment]
Could you please answer the questions from the issue template so we can help you to debug this:

### PhoneGap CLI, node & npm versions

### Expected Behaviour

### Actual Behaviour

### Steps to Reproduce 

#### Sample Code that illustrates the problem

#### Error messages
