### ISSUE TITLE
The platform "ios" does not appear to be a valid cordova platform

### ISSUE THREAD

**Issue by thesequelgroup** [phonegap/phonegap-cli#753]
I **constantly** get the below error when installing any cordova plugin. The final result seems to be everything works after the build process, but I'd really like to know why this always happens? Why is iOS always appear to be an invalid platform? I've removed and add it several times. The result is the same. Note that I'm on a Windows 10 machine.

### PhoneGap CLI, node & npm versions
npm 5.4.2
PhoneGap (iOS / Android / Windows)
cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3)
### Expected Behaviour
Install without errors?

#### Sample Code that illustrates the problem
cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME=uniquename

#### Error messages
`Failed to install 'cordova-plugin-customurlscheme': Error: Uncaught, unspecified "error" event. (The platform "         ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.)
    at EventEmitter.emit (events.js:163:17)
    at EventEmitter.module.exports.emit (C:\Users\Matt\AppData\Roaming\npm\node_modules\cordova\node_modules\co         rdova-common\src\events.js:71:17)
    at Object.getPlatformApiFunction (C:\Users\Matt\AppData\Roaming\npm\node_modules\cordova\node_modules\cordo         va-lib\src\cordova\util.js:500:20)
    at Object.getPlatformApi (C:\Users\Matt\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\s         rc\platforms\platforms.js:55:25)
    at handleInstall (C:\Users\Matt\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugm         an\install.js:593:29)
    at C:\Users\Matt\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:3         57:28
    at _fulfilled (C:\Users\Matt\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Matt\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:81         6:30)
    at Promise.promise.promiseDispatch (C:\Users\Matt\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q         .js:749:13)
    at C:\Users\Matt\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
Error: Uncaught, unspecified "error" event. (The platform "ios" does not appear to be a valid cordova platform.          It is missing API.js. ios not supported.)
`

**Comment by t2wu** [comment]
Any solution to this? I run into this error as well.

**Comment by lkrubner** [comment]
I have the same issue. But nothing seems to get the system working for me. 

I do this:

    ionic cordova build

and I get:

    
    [WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.
    
    ? What platform would you like to build (android, ios): ios
    [WARN] Detected @ionic/cli-plugin-cordova in your package.json.
    
           As of CLI 3.8, it is no longer needed. You can uninstall it:
           
           npm uninstall -D @ionic/cli-plugin-cordova
           
    
    Running app-scripts build: --platform ios --target cordova
    [19:21:23]  build dev started ... 
    [19:21:24]  clean started ... 
    [19:21:24]  clean finished in 87 ms 
    [19:21:24]  copy started ... 
    [19:21:24]  transpile started ... 
    [19:21:51]  transpile finished in 26.45 s 
    [19:21:51]  preprocess started ... 
    [19:21:51]  deeplinks started ... 
    [19:21:55]  deeplinks finished in 4.27 s 
    [19:21:55]  preprocess finished in 4.27 s 
    [19:21:55]  webpack started ... 
    [19:22:01]  copy finished in 36.91 s 
    [19:22:28]  webpack finished in 33.03 s 
    [19:22:28]  sass started ... 
    [19:22:35]  sass finished in 6.37 s 
    [19:22:35]  postprocess started ... 
    [19:22:35]  removed unused font files 
    [19:22:35]  postprocess finished in 288 ms 
    [19:22:35]  lint started ... 
    [19:22:35]  build dev finished in 72.01 s 
    > cordova build ios
    Unable to load PlatformApi from platform. Error: Cannot find module 'unorm'
    
    Error: Uncaught, unspecified "error" event. (The platform "ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.)
    
    [ERROR] An error occurred while running cordova build ios (exit code 1).



My ionic info:

    
    ionic info
    [WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.
    
    cli packages: (/usr/local/lib/node_modules)
    
        @ionic/cli-utils  : 1.19.2
        ionic (Ionic CLI) : 3.20.0
    
    global packages:
    
        cordova (Cordova CLI) : 7.1.0 
    
    local packages:
    
        @ionic/app-scripts : 2.1.4
        Cordova Platforms  : android 6.2.3 ios 4.4.0
        Ionic Framework    : ionic-angular 3.6.0
    
    System:
    
        Android SDK Tools : 26.0.1
        ios-deploy        : 1.9.2 
        Node              : v6.5.0
        npm               : 5.8.0 
        OS                : macOS High Sierra
        Xcode             : Xcode 9.2 Build version 9C40b 
    
    Environment Variables:
    
        ANDROID_HOME : /usr/local/Caskroom/android-sdk/3859397/
    
    Misc:
    
        backend : pro

**Comment by purplecabbage** [comment]
`phonegap build ios` will install ios
Not sure what is happening here, something between ionic, and phonegap cli perhaps.
Please update phonegap to 8.0.0, if this issue still happens, please re-open this issue.

**Comment by mkyukov** [comment]
Having the same issue on cordova 8.0.0.

**Comment by linigithub** [comment]
Thanks @AmareshB 
I installed latest nodejs version , cordova version
remove and add ios platform. error solved.

**Comment by MJames007** [comment]
> I had the same issue.
> I just updated node to the latest version.
> 
> `cordova platform rm ios cordova platform add ios`
> 
> This solved the issue for me.

this works :P
