### ISSUE TITLE
Can't define icons for windows platform using pgb 7.0.1 cli

### ISSUE THREAD

**Issue by wemersonjanuario** [phonegap/phonegap-cli#756]
### PhoneGap CLI, node & npm versions
PGB CLI 7.0.1
### Expected Behaviour
create correct and custom icons for the app
### Actual Behaviour
failure while remote building for windows platform
### Steps to Reproduce 
phonegap create myapp com.company.MyApp MyApp
phonegap platform add windows

define phonegap cli 7.0.1 as phonegap version in config.xml
<preference name="phonegap-version" value="cli-7.0.1"/>

Define your icons

<platform name="windows">
        <icon height="150" platform="windows" src="www/res/icon/windows/Square150x150Logo.scale-100.png" width="150" />
        <icon height="30" platform="windows" src="www/res/icon/windows/Square30x30Logo.scale-100.png" width="30" />
        <icon height="50" platform="windows" src="www/res/icon/windows/StoreLogo.scale-100.png" width="50" />
        <splash height="300" platform="windows" src="www/res/screen/windows/SplashScreen.scale-100.png" width="620" />
        <icon height="120" platform="windows" src="www/res/icon/windows/StoreLogo.scale-240.png" width="120" />
        <icon height="44" platform="windows" src="www/res/icon/windows/Square44x44Logo.scale-100.png" width="44" />
        <icon height="106" platform="windows" src="www/res/icon/windows/Square44x44Logo.scale-240.png" width="106" />
        <icon height="70" platform="windows" src="www/res/icon/windows/Square70x70Logo.scale-100.png" width="70" />
        <icon height="71" platform="windows" src="www/res/icon/windows/Square71x71Logo.scale-100.png" width="71" />
        <icon height="170" platform="windows" src="www/res/icon/windows/Square71x71Logo.scale-240.png" width="170" />
        <icon height="360" platform="windows" src="www/res/icon/windows/Square150x150Logo.scale-240.png" width="360" />
        <icon height="310" platform="windows" src="www/res/icon/windows/Square310x310Logo.scale-100.png" width="310" />
        <icon height="150" platform="windows" src="www/res/icon/windows/Wide310x150Logo.scale-100.png" width="310" />
        <icon height="360" platform="windows" src="www/res/icon/windows/Wide310x150Logo.scale-240.png" width="744" />
        <splash height="1920" platform="windows" src="www/res/screen/windows/SplashScreenPhone.scale-240.png" width="1152" />
    </platform>

phonegap remote login username="you@domai.com" password="yourpassword"
phonegap remote build windows
#### Error messages
phonegab build windows log ends  with this error
Updating icons and splash screens at ..\project\images
Error: Source path does not exist: www/res/screen/windows/SplashScreen.scale-100.png
    at updatePathInternal (C:\project\cordova\node_modules\cordova-common\src\FileUpdater.js:145:19)
    at C:\project\cordova\node_modules\cordova-common\src\FileUpdater.js:223:19
    at Array.forEach (native)
    at Object.updatePaths (C:\project\cordova\node_modules\cordova-common\src\FileUpdater.js:221:33)
    at copyImages (C:\project\cordova\lib\prepare.js:444:17)
    at C:\project\cordova\lib\prepare.js:615:9
    at _fulfilled (C:\project\cordova\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\project\cordova\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\project\cordova\node_modules\q\q.js:796:13)
    at C:\project\cordova\node_modules\q\q.js:604:44

**Comment by tisdall** [comment]
I'm having this same issue but with finding other resources.  Has anyone found a solution?

**Comment by tisdall** [comment]
ugh!  found it finally!  The new system starts looking for paths within the "www" directory so your

`<splash height="300" platform="windows" src="www/res/screen/windows/SplashScreen.scale-100.png" width="620" />` 

should be changed to 

`<splash height="300" platform="windows" src="res/screen/windows/SplashScreen.scale-100.png" width="620" />`

I couldn't find this commented about ANY WHERE and just happened to find a single comment on an Adobe forum suggesting to remove the "www/".
