### ISSUE TITLE
Blank project gets "Path must be a string, Received undefined"

### ISSUE THREAD

**Issue by Stylesoftware** [phonegap/phonegap-cli#759]
### PhoneGap CLI, node & npm versions
Phonegap CLI v 7.1.1
Cordova v 8.0.0
Node v 8.9.4
NPM v 5.6.0
OS Win7

### Expected Behaviour
Open browser, connect to ip:3000
no error in CLI

### Actual Behaviour
'Type' (error as shown below) in CLI as soon as browser connects

### Steps to Reproduce 
prompt:>phonegap create wmt4 --name wmt4 --template blank
prompt:>cd wmt4
prompt:>phonegap serve
action: connect to ip:3000 using chrome

#### Sample Code that illustrates the problem
No code changes; Blank template

#### Reinstall, no change in error:
npm -g remove cordova
npm -g remove phonegap
npm cache clean --force
npm install phonegap
npm install cordova

#### Error messages
[phonegap] starting app server...
[phonegap] listening on 192.168.0.110:3000
[phonegap]
[phonegap] ctrl-c to stop the server
[phonegap]
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=M4YRQGy
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=M4YRQL6&sid=XjX5uSLu3TF9_R8vAAAA
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=M4YRQLM&sid=XjX5uSLu3TF9_R8vAAAA
[phonegap] 200 /
[phonegap] 304 /socket.io/socket.io.js
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:499:7)
    at Object.handle (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\lib\middleware\cordova\cordova.
js:21:33)
    at next (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect\lib\proto.js:174:15)
    at SendStream.error (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\phonegap\node_modules\serve-static\index.js:120:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\phonegap\node_modules\send\index.js:245:17)
    at SendStream.onStatError (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\phonegap\node_modules\send\index.js:356:12)
    at onstat (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\phonegap\node_modules\send\index.js:621:26)
[phonegap] 500 /cordova.js
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=M4YRQYf
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=M4YRQa4&sid=lbTSniYEv8iaQafcAAAB
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=M4YRQaK&sid=lbTSniYEv8iaQafcAAAB

**Comment by surajpindoria** [comment]
Hi @Stylesoftware,

This error typically comes up when you try to load the app in the browser before it has fully been added to your project. After running `phonegap serve` if you give it a second to add the browser platform it should be fine. Also if you do see that error and try reloading the page it should go away once the platform has been added.

**Comment by Stylesoftware** [comment]
Unfortunately the error happens on every page load, 
Also Waiting for 30 seconds does nothing either.
I have a feeling it must be to do with me downgrading NodeJS then finding these problems, then re-upgrading, a few days ago, 
I'll try wiping all remnants of node/cordova/android platform/phonegap, and reinstalling, its all I can think to do.

**Comment by Stylesoftware** [comment]
Hi Surajpindoria,

Okay so I did a big cleanout, removing all remnants of node and phonegap and node_modules and node_caches etc.
The error still persists, on new projects, but I notice the error doesn't occur in my existing projects.

I've managed to create a new project 5 times, and each time the error is there.
However after adding some plugins and android platform, the error goes away, sometimes when I add the very first plugin, sometimes when I edit the HTML file, sometimes when I add the android platform.

Perhaps some kind of caching problem?

I've tried with Chrome developer tools open to stop browser side caching, tried Firefox, no change in the randomness.

One thing is persistent,(atleast with my OS) A new project without modification will always give the error.
And requires some modifications for the error to go away, and once away it never comes back. 

I have a coupla project zip files if your interested, one with a new project that will give the error and another with a project that won't, they both have one plugin added, and no changes to any other file from the project create process.

So no biggie, but annoying.

**Comment by flieks** [comment]
@Stylesoftware i have the same problem but what or how much do you have to change to get it to work? it's because it can't find cordova.js & bundle.js on the root

**Comment by bhavincb** [comment]
+1

**Comment by ryanhornberger** [comment]
+1

**Comment by DivySrivastava** [comment]
I had the same error..
Just reloading the page fixed it for me.

![image](https://user-images.githubusercontent.com/34997667/54488279-f48ab900-48c5-11e9-89fb-2034b8d2d297.png)
