### ISSUE TITLE
cordova-plugin-inappbrowser does not work with 8.0.0+

### ISSUE THREAD

**Issue by jonhue** [phonegap/phonegap-cli#761]
PhoneGap CLI: 8.0.0

### Expected Behaviour

No errors

### Actual Behaviour

Processing with PhoneGap Build throws the following error:

```
Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-inappbrowser@~2.0.2" via npm Installing "cordova-plugin-inappbrowser" at "2.0.2" for android Failed to install 'cordova-plugin-inappbrowser': Error: ENOENT: no such file or directory, open '/tmp/gimlet/24541400/2805560/www_android/AndroidManifest.xml' at Error (native) at Object.fs.openSync (fs.js:640:18) at Object.fs.readFileSync (fs.js:508:33) at Object.parseElementtreeSync (/tmp/gimlet/24541400/2805560/www_android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27) at new AndroidManifest (/tmp/gimlet/24541400/2805560/www_android/cordova/lib/AndroidManifest.js:29:20) at AndroidProject.getPackageName (/tmp/gimlet/24541400/2805560/www_android/cordova/lib/AndroidProject.js:99:12) at Api.addPlugin (/tmp/gimlet/24541400/2805560/www_android/cordova/Api.js:223:57) at handleInstall (/home/ec2-user/.npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:594:10) at /home/ec2-user/.npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:364:24 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:787:54) ENOENT: no such file or directory, open '/tmp/gimlet/24541400/2805560/www_android/AndroidManifest.xml' - You can fix this here
```

My config:

```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.phylator" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:gap="http://phonegap.com/ns/1.0">

    <engine name="android" spec="~6.3.0" />
    <plugin name="cordova-plugin-inappbrowser" source="npm" spec="~2.0.2" />
    <preference name="phonegap-version" value="cli-8.0.0" />

    <!-- ... -->

</widget>
```

Changing the PhoneGap version to `cli-7.1.0` resolves the issue.

**Comment by axilaris** [comment]
how did you reconfigure your cordova from 8.0.0 yo 7.1.0 ?

**Comment by jonhue** [comment]
@axilaris

I did not change anything except the PhoneGap CLI version.

**Comment by goya** [comment]
unable to replicate the issue. it might be related to other parts of your config.xml

did you open an issue at the phonegap build forum?  https://forums.adobe.com/community/phonegap/build
