### ISSUE TITLE
Phonegap install android failing on windows (local)

### ISSUE THREAD

**Issue by textoo** [phonegap/phonegap-cli#77]
maybe it's me, i'm a noob with phonegap cli,

my Android SDK is OK and in the Path (i can create and compile phonegap/cordova 2.5 projects in eclipse),
here is what i get in the node prompt as administrator while creating a basic project:

```
> E:\repositories>phonegap create helloworld

  phonegap  created project at E:\repositories\helloworld

> E:\repositories>cd helloworld
> E:\repositories\helloworld>phonegap install android

  phonegap  detecting Android SDK environment...
  phonegap  using the local environment

C:\Users\Tex\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordva\src\metadata\android_parser.js:35
        throw new Error('The provided path "' + project + '" is not an Android
              ^
Error: The provided path "E:\repositories\helloworld\platforms\android" is not an Android project.
    at Object.android_parser (C:\Users\Tex\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\src\metadata\android_parser.js:35:15)
    at C:\Users\Tex\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\src\prepare.js:67:23
    at Array.map (native)
    at Object.prepare (C:\Users\Tex\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\src\prepare.js:65:30)
    at C:\Users\Tex\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\src\run.js:105:35
    at C:\Users\Tex\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\src\hooker.js:65:25
    at execute_scripts_serially (C:\Users\Tex\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\src\hooker.js:92:9)
    at C:\Users\Tex\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\src\hooker.js:61:17
    at execute_handlers_serially (C:\Users\Tex\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\src\hooker.js:108:9)
    at Object.fire (C:\Users\Tex\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\src\hooker.js:55:9)
```

i've noticed that there is no "android" folder created in the "platforms" folder of the project
i'm running Win7 64

**Comment by santhosh77h** [comment]
when i run phonegap i'm geeting this errror module not fiound   **..\..\node_modules\cordova\node_modules\cordova-lib**  **node  v4.1.0 npm 3.3.3 **
