### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by SamanthaSingh** [phonegap/phonegap-cli#771]
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at PushCommand.execute (C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\push.js:71:25)
    at PushCommand.run (C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\push.js:51:10)
    at PhoneGap.push (C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\util\command.js:28:25)
    at CLI.module.exports [as push] (C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\lib\cli\push.js:27:14)
    at CLI.module.exports [as argv] (C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\lib\cli\argv.js:111:17)
    at runPhoneGapCommand (C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js:46:9)
    at Object.<anonymous> (C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js:38:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)

**Comment by purplecabbage** [comment]
What did you execute to get this error?
Please include steps to reproduce this error.

**Comment by SamanthaSingh** [comment]
C:\Users\corne\Desktop\Push Notifications Demo\Push Notifications
Demo>phonegap push --deviceID
eHnlbLjHJ8k:APA91bExm-O608zd34VhyykoSj2HUI-yTirB-thM5EpbARmJLqx0etZERW37hTE0epDucNfp1FRT0ZiwMxpma5vNE9CdwSeyLNi_M2tQ_9Sm-6vUQBUx6ICs4A8BlNZv3EH-56hzqWbM
--service fcm --payload '{ "data": { "title": "Hello", "message": "World"}
}'
There was an unhandled exception within phonegap-cli! If you would like to
help the PhoneGap project, please file the following details over at
https://github.com/phonegap/phonegap-cli/issues
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at PushCommand.execute
(C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\push.js:71:25)
    at PushCommand.run
(C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\push.js:51:10)
    at PhoneGap.push
(C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\util\command.js:28:25)
    at CLI.module.exports [as push]
(C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\lib\cli\push.js:27:14)
    at CLI.module.exports [as argv]
(C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\lib\cli\argv.js:111:17)
    at runPhoneGapCommand
(C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js:46:9)
    at Object.<anonymous>
(C:\Users\corne\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js:38:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)

**Comment by purplecabbage** [comment]
You should have received a push notification from me! 
_Note: I have removed your deviceId from this issue._
It seems like you probably had a new line in your input, try again with:
` phonegap push --deviceID DEVICE_ID --service fcm --payload '{ "data": { "title": "Hello", "message": "World"}}' `

**Comment by SamanthaSingh** [comment]
Thanks. Its working now
