### ISSUE TITLE
Phonegap Serve not working

### ISSUE THREAD

**Issue by harshit101** [phonegap/phonegap-cli#779]
I got this error when I try to run this in command line
$ phonegap serve
[phonegap] starting app server...
[phonegap] listening on 192.168.1.98:3000
[phonegap] listening on 192.168.56.1:3000
[phonegap] listening on 192.168.10.1:3000
[phonegap]
[phonegap] ctrl-c to stop the server
[phonegap]
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=MCgZgeE
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=MCgZmkw
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=MCgZsrc
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=MCgZyyI
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=MCga32z
[phonegap] 200 /socket.io/?EIO=3&transport=polling&t=MCga4Gh&sid=iYGTw_S7pPhr9fK                     kAAAE
There was an unhandled exception within phonegap-cli! If you would like to help                      the PhoneGap project, please file the following details over at https://github.c                     om/phonegap/phonegap-cli/issues
TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (C:\Users\harshit\AppD                     ata\Roaming\nvm\v8.0.0\node_modules\phonegap\node_modules\compress-commons\lib\a                     rchivers\zip\zip-archive-output-stream.js:184:11)
    at module.exports.ZipArchiveOutputStream._appendStream (C:\Users\harshit\App                     Data\Roaming\nvm\v8.0.0\node_modules\phonegap\node_modules\compress-commons\lib\                     archivers\zip\zip-archive-output-stream.js:96:20)
    at module.exports.ArchiveOutputStream.entry (C:\Users\harshit\AppData\Roamin                     g\nvm\v8.0.0\node_modules\phonegap\node_modules\compress-commons\lib\archivers\a                     rchive-output-stream.js:88:10)
    at module.exports.ZipStream.entry (C:\Users\harshit\AppData\Roaming\nvm\v8.0                     .0\node_modules\phonegap\node_modules\zip-stream\index.js:157:49)
    at Zip.append (C:\Users\harshit\AppData\Roaming\nvm\v8.0.0\node_modules\phon                     egap\node_modules\connect-phonegap\node_modules\archiver\lib\plugins\zip.js:53:1                     5)
    at Archiver._moduleAppend (C:\Users\harshit\AppData\Roaming\nvm\v8.0.0\node_                     modules\phonegap\node_modules\connect-phonegap\node_modules\archiver\lib\core.js                     :166:16)
    at Archiver._onQueueTask (C:\Users\harshit\AppData\Roaming\nvm\v8.0.0\node_m                     odules\phonegap\node_modules\connect-phonegap\node_modules\archiver\lib\core.js:                     364:8)
    at C:\Users\harshit\AppData\Roaming\nvm\v8.0.0\node_modules\phonegap\node_mo                     dules\async\dist\async.js:4082:9
    at Object.process (C:\Users\harshit\AppData\Roaming\nvm\v8.0.0\node_modules\                     phonegap\node_modules\async\dist\async.js:2330:17)

**Comment by maverickmishra** [comment]
Please follow the [Issue Template](https://github.com/phonegap/phonegap-cli/blob/master/.github/ISSUE_TEMPLATE.md) to explain this issue clearly.

**Comment by purplecabbage** [comment]
Cannot reproduce without more details.
If this is still happening consistently, please provide more details and reopen this issue.
