### ISSUE TITLE
`phonegap run ios` build fails

### ISSUE THREAD

**Issue by raineorshine** [phonegap/phonegap-cli#780]
### PhoneGap CLI, node & npm versions
phonegap-cli v8.0.0
node v8.9.4
npm v5.6.0
OSX v10.13.4

### Expected Behaviour
Helloworld project should build and run in simulator.

### Actual Behaviour
Build fails as seen below. I have `ios-sim` and `ios-deploy --unsafe-perm` installed.

### Steps to Reproduce 

```
phonegap run ios
```

#### Sample Code that illustrates the problem
Default Helloworld project.

#### Error messages

```
[36m[phonegap][39m executing 'cordova run ios' ...
Discovered plugin "cordova-plugin-file-transfer" in config.xml. Adding it to the project


Plugin "cordova-plugin-file-transfer" already installed on browser.


Installing "cordova-plugin-file-transfer" for ios


Failed to install 'cordova-plugin-file-transfer': CordovaError: Version of installed plugin: "cordova-plugin-file@6.0.1" does not satisfy dependency plugin requirement "cordova-plugin-file@^4.0.0". Try --force to use installed plugin as dependency.
    at /Users/raine/.nvm/versions/node/v8.9.4/lib/node_modules/phonegap/node_modules/cordova-lib/src/plugman/install.js:557:37
    at _fulfilled (/Users/raine/.nvm/versions/node/v8.9.4/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/raine/.nvm/versions/node/v8.9.4/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/raine/.nvm/versions/node/v8.9.4/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /Users/raine/.nvm/versions/node/v8.9.4/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/q/q.js:509:49
    at flush (/Users/raine/.nvm/versions/node/v8.9.4/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)


Failed to restore plugin "cordova-plugin-file-transfer" from config.xml. You might need to try adding it again. Error: Version of installed plugin: "cordova-plugin-file@6.0.1" does not satisfy dependency plugin requirement "cordova-plugin-file@^4.0.0". Try --force to use installed plugin as dependency.

...

Ld build/emulator/phonegap-helloworld.app/phonegap-helloworld normal x86_64
    cd /Users/raine/projects/phonegap-helloworld/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/raine/.nvm/versions/node/v8.9.4/bin:.cabal-sandbox/bin:/Users/raine/Library/Haskell/bin:./node_modules/.bin:~/bin:/Library/Frameworks/Python.framework/Versions/3.3/bin:/usr/local/heroku/bin:/Users/raine/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.3.sdk -L/Users/raine/projects/phonegap-helloworld/platforms/ios/build/emulator -F/Users/raine/projects/phonegap-helloworld/platforms/ios/build/emulator -filelist /Users/raine/Library/Developer/Xcode/DerivedData/phonegap-helloworld-bkknofcrhgqxgygsnhjbnohiuwas/Build/Intermediates.noindex/phonegap-helloworld.build/Debug-iphonesimulator/phonegap-helloworld.build/Objects-normal/x86_64/phonegap-helloworld.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/raine/Library/Developer/Xcode/DerivedData/phonegap-helloworld-bkknofcrhgqxgygsnhjbnohiuwas/Build/Intermediates.noindex/phonegap-helloworld.build/Debug-iphonesimulator/phonegap-helloworld.build/Objects-normal/x86_64/phonegap-helloworld_lto.o -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/raine/Library/Developer/Xcode/DerivedData/phonegap-helloworld-bkknofcrhgqxgygsnhjbnohiuwas/Build/Intermediates.noindex/phonegap-helloworld.build/Debug-iphonesimulator/phonegap-helloworld.build/phonegap-helloworld.app-Simulated.xcent /Users/raine/projects/phonegap-helloworld/platforms/ios/build/emulator/libCordova.a -weak_framework ImageIO -framework CoreLocation -framework AVFoundation -weak_framework AddressBook -weak_framework AddressBookUI -lz -framework CoreMotion -weak_framework AudioToolbox -Xlinker -dependency_info -Xlinker /Users/raine/Library/Developer/Xcode/DerivedData/phonegap-helloworld-bkknofcrhgqxgygsnhjbnohiuwas/Build/Intermediates.noindex/phonegap-helloworld.build/Debug-iphonesimulator/phonegap-helloworld.build/Objects-normal/x86_64/phonegap-helloworld_dependency_info.dat -o /Users/raine/projects/phonegap-helloworld/platforms/ios/build/emulator/phonegap-helloworld.app/phonegap-helloworld

duplicate symbol _OBJC_CLASS_$_CDVLogger in:
    /Users/raine/Library/Developer/Xcode/DerivedData/phonegap-helloworld-bkknofcrhgqxgygsnhjbnohiuwas/Build/Intermediates.noindex/phonegap-helloworld.build/Debug-iphonesimulator/phonegap-helloworld.build/Objects-normal/x86_64/CDVLogger.o
    /Users/raine/projects/phonegap-helloworld/platforms/ios/build/emulator/libCordova.a(CDVLogger.o)
duplicate symbol _OBJC_METACLASS_$_CDVLogger in:
    /Users/raine/Library/Developer/Xcode/DerivedData/phonegap-helloworld-bkknofcrhgqxgygsnhjbnohiuwas/Build/Intermediates.noindex/phonegap-helloworld.build/Debug-iphonesimulator/phonegap-helloworld.build/Objects-normal/x86_64/CDVLogger.o
    /Users/raine/projects/phonegap-helloworld/platforms/ios/build/emulator/libCordova.a(CDVLogger.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)



** BUILD FAILED **


The following build commands failed:

	Ld build/emulator/phonegap-helloworld.app/phonegap-helloworld normal x86_64
(1 failure)

(node:11305) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error code 65 for command: xcodebuild with args: -xcconfig,/Users/raine/projects/phonegap-helloworld/platforms/ios/cordova/build-debug.xcconfig,-workspace,phonegap-helloworld.xcworkspace,-scheme,phonegap-helloworld,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/raine/projects/phonegap-helloworld/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/raine/projects/phonegap-helloworld/platforms/ios/build/sharedpch

(node:11305) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Full output: https://gist.github.com/raineorshine/cc7211d93495eef44d8b945b065edebf

**Comment by maverickmishra** [comment]
I was not able to replicate your issue with phonegap cli v8.0.0, node v8.11.2 on macOS High Sierra. It seems from your logs that there is a problem in installation of the cordova-plugin-file-transfer plugin which is caused by the dependency plugin cordova-plugin-file. Can you provide the exact steps to reproduce your error?

**Comment by raineorshine** [comment]
@maverickmishra Yes, I created the HelloWorld project, and then ran `phonegap run ios`. This command never completes, with the error message shown above.

**Comment by raineorshine** [comment]
@purplecabbage Sorry for the delay, I was out of town. I am using the cli. Yes, this still occurs.
