### ISSUE TITLE
Phonegap Remote Build Failing

### ISSUE THREAD

**Issue by mrspinn** [phonegap/phonegap-cli#783]
I'm trying to use phonegap-cli to build my app remotely. My command is "$phonegap remote build android" and it fails on the upload step with the error below. It happens on every app including a fresh app. If there's any other information I can supply to help diagnose the issue, please let me know and I'll get it promptly! Thanks for any help!

### PhoneGap CLI, node & npm versions
Phonegap 8.0.0
node 10.4.0
npm 6.1.0

### Expected Behaviour
$ phonegap remote build android
This should compress and build the app

### Actual Behaviour
Fails on upload

### Steps to Reproduce 
1. Create an app using $phonegap create
2. Run $phonegap remote build android
3. Fails on upload
It happens on every app I try to build. Even the default "Hello, World" app.

#### Error messages
There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:167:11)
    at Object.fs.rmdir (fs.js:810:14)
    at Object.cleanup (C:\Users\ssfro\AppData\Roaming\npm\node_modules\phonegap\node_modules\phonegap-build\lib\phonegap-build\create\zip.js:119:16)
    at Object.callback (C:\Users\ssfro\AppData\Roaming\npm\node_modules\phonegap\node_modules\phonegap-build\lib\phonegap-build\build\remote.js:71:21)
    at Request._callback (C:\Users\ssfro\AppData\Roaming\npm\node_modules\phonegap\node_modules\phonegap-build-api\lib\api.js:230:26)
    at Request.self.callback (C:\Users\ssfro\AppData\Roaming\npm\node_modules\phonegap\node_modules\phonegap-build-api\node_modules\request\main.js:122:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\ssfro\AppData\Roaming\npm\node_modules\phonegap\node_modules\phonegap-build-api\node_modules\request\main.js:655:16)
    at Request.emit (events.js:187:15)
    at IncomingMessage.<anonymous> (C:\Users\ssfro\AppData\Roaming\npm\node_modules\phonegap\node_modules\phonegap-build-api\node_modules\request\main.js:617:14)

**Comment by roarkmccolgan** [comment]
Same for me:
PG: 8
npm: 5.6
node: 10.1

**Comment by mrspinn** [comment]
I actually solved my issue. It had to do with the version of node.js
I re-installed with node 8.11.2 and it works now.
