### ISSUE TITLE
unhandled exception PhoneGap cli

### ISSUE THREAD

**Issue by dmplshrm** [phonegap/phonegap-cli#799]

**Comment by dmplshrm** [comment]
can someone help me with this... i am new with this and not able to understand.....

 project directory could not be found
There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
TypeError: Cannot read property 'then' of undefined
    at AppCommand.run (C:\Users\user\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\serve.js:87:43)
    at PhoneGap.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\phonegap\lib\phonegap\util\command.js:28:25)    at CLI.module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\phonegap\lib\cli\serve.js:36:14)
    at CLI.module.exports [as argv] (C:\Users\user\AppData\Roaming\npm\node_modules\phonegap\lib\cli\argv.js:111:17)
    at runPhoneGapCommand (C:\Users\user\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js:46:9)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js:38:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)

**Comment by rkar008** [comment]
Even i have same issue.

**Comment by frederikbosch** [comment]
I think this [is related to Node 10](https://github.com/phonegap/node-phonegap-build/pull/69).
