### ISSUE TITLE
Error on remote builder android linux

### ISSUE THREAD

**Issue by ribafs** [phonegap/phonegap-cli#810]
### PhoneGap CLI, node & npm versions
Phonegap 8.2.2
node - 11.14
npm - 6.7

### Expected Behaviour
Compile to builder
### Actual Behaviour
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:141:11)
    at Object.rmdir (fs.js:687:14)
    at Object.cleanup (/usr/lib/node_modules/phonegap/node_modules/phonegap-build/lib/phonegap-build/create/zip.js:119:16)
    at Object.callback (/usr/lib/node_modules/phonegap/node_modules/phonegap-build/lib/phonegap-build/create/remote.js:83:21)
    at Request._callback (/usr/lib/node_modules/phonegap/node_modules/phonegap-build-api/lib/api.js:214:22)
    at Request.self.callback (/usr/lib/node_modules/phonegap/node_modules/request/request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.<anonymous> (/usr/lib/node_modules/phonegap/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:193:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/phonegap/node_modules/request/request.js:1083:12)

### Steps to Reproduce 
On linux mint 19.1
phonegap remote build android
#### Sample Code that illustrates the problem
https://github.com/ribafs/breakout-br

**Comment by andersborgabiro** [comment]
It's still this way. Any way to escalate?

**Comment by andersborgabiro** [comment]
I just updated everything (node, cordova, phonegap, npm) and I still get the same result, in my case on Windows.

npm: 6.10.1
node: 10.16.0 (lower than for @ribafs, but the official version)
cordova: 9.0.0
phonegap: 8.2.2 (released November 2018)

**Comment by dbessa1** [comment]
também estou com o mesmo problema
