### ISSUE TITLE
Phonegap remote build failed

### ISSUE THREAD

**Issue by LasseAtomic** [phonegap/phonegap-cli#814]
I'am trying to remote build the clean hello world app.
After zipping and uploading file the phonegap crashes

I noticed and old error where the fix was to update note.js to v11, I have updated to v12 without any changes

### PhoneGap CLI, node & npm versions
Phonegap 8.2.2
Windows 2012 server
NPM 10.14 and 12.7

### Expected Behaviour
Build success

### Actual Behaviour
Crashs

### Steps to Reproduce 
Create hello world, build remote

#### Error messages
$phonegap remote build ios

[phonegap] compressing the app...
[phonegap] uploading the app...
There was an unhandled exception within phonegap-cli! If you would like to help
the PhoneGap project, please file the following details over at https://github.c
om/phonegap/phonegap-cli/issues
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefine
d
    at makeCallback (fs.js:150:11)
    at Object.rmdir (fs.js:682:14)
    at Object.cleanup (C:\Users\Administrator\AppData\Roaming\npm\node_modules\p
honegap\node_modules\phonegap-build\lib\phonegap-build\create\zip.js:119:16)
    at Object.callback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\
phonegap\node_modules\phonegap-build\lib\phonegap-build\create\remote.js:83:21)
    at Request._callback (C:\Users\Administrator\AppData\Roaming\npm\node_module
s\phonegap\node_modules\phonegap-build-api\lib\api.js:214:22)
    at Request.self.callback (C:\Users\Administrator\AppData\Roaming\npm\node_mo
dules\phonegap\node_modules\request\request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modu
les\phonegap\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\n
ode_modules\phonegap\node_modules\request\request.js:1083:12)

**Comment by LarsVoith** [comment]
I'm coming up with the same problem. Our team has purchase the Creative Cloud for the use of the build services on PhoneGap, it would really be appreciated if someone could support us over in Adobe?


There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.rmdir (fs.js:667:14)
    at Object.cleanup (/usr/local/lib/node_modules/phonegap/node_modules/phonegap-build/lib/phonegap-build/create/zip.js:119:16)
    at Object.callback (/usr/local/lib/node_modules/phonegap/node_modules/phonegap-build/lib/phonegap-build/create/remote.js:83:21)
    at Request._callback (/usr/local/lib/node_modules/phonegap/node_modules/phonegap-build-api/lib/api.js:230:26)
    at Request.self.callback (/usr/local/lib/node_modules/phonegap/node_modules/request/request.js:185:22)

    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/phonegap/node_modules/request/request.js:1083:12)

**Comment by purplecabbage** [comment]
strange issue, thanks for posting the stack trace.

**Comment by Gamedevolop** [comment]
![Image 5](https://user-images.githubusercontent.com/29807639/64134044-9b123a00-cdd2-11e9-8007-105a0b05b5b7.png)
same here

**Comment by nickcdavis** [comment]
Also receiving the same issue.

**Comment by justinfransen** [comment]
Same issue.

**Comment by Gamedevolop** [comment]
I tried it on Mac also and has the same problem

**Comment by DanTheMan-NL** [comment]
Same issue here

**Comment by andersborgabiro** [comment]
The exact same error here too. I'd save time by using this tool, so it's a bummer it doesn't work anymore. It looks like a trivial issue too.

I updated to the latest node, cordova and phonegap just now, to see if it changed. It didn't.

**Comment by DanTheMan-NL** [comment]
I found a dirty workaround. Since I don't own a mac I am stuck with phonegap build to build for iOS but I hope it will be fixed soon. 

I remove my project from build.phonegap.com
Build with phonegap cli: phonegap remote build ios
I receive the error above but my project is uploaded to build.phonegap.com
I use the website build/rebuild button to build my .ipa file

Sometimes the build won't upload on the first try then I try to upload again and eventually the project will apear in build.phonegap.com

Hope this will help someone.

**Comment by andersborgabiro** [comment]
I have PCs with Windows, macOS and Linux, so I use PGB because convenience:
* The local project only contains my source and nothing else, so backups and release archiving are easy,
* It builds for all platforms I need autonomously.
* It handles the certificate logistics.

Anywho 1: Why did you have to remove the project first? If the upload part works, you shouldn't have to.

Anywho 2: When I run phonegap remote on an existing project it actually uploads the code and starts building, so the error happens after those stages. I didn't have to remove the project. Mileage may vary.

**Comment by LasseAtomic** [comment]
I'm using almost same workaround.
Even with the "crash on upload" this tread is about, it seems to work with the remote build for the first upload.. But it seemed not to work on following remote builds.

So my setup is - all automated
- Delete old app in PGB
- Start new remote build
- Activate certificates on PGB via api
- Wait for build to finish
- Upload .idp file to apple via another api

**Comment by andersborgabiro** [comment]
@LasseAtomic For me it uploads and builds correctly multiple times as-is. I checked by changing the version.

I used "call phonegap remote --no-proxy build android".

**Comment by DanTheMan-NL** [comment]
@andersborgabiro I read somewhere the error has something to do with PGB not being able to clean up. Therefore it seems logic to me the upload works again whenever I delete the project myself.

**Comment by andersborgabiro** [comment]
I've built 10ish times since I posted and they all succeeded with no handholding.

But fixing the bug is still needed, a year or so after its inception.

**Comment by LasseAtomic** [comment]
Hi Guys
New update on this issue.

As I mentioned we using an automated setup to delete and build the app.

Behind this there is a build of an angular app, from where the output is copied into the phonegap/www and then starting the build.

Today when my angular developer have done a number of changes, the phonegap have stopped working. No changes has been done to the phonegap environement etc, only to the content of the /www/ folder (and I have tried with an older version of that folder...

The "look and feel" of the error is unchanged. I get the exact same crash as in the first post of july 30th, but now the app is newer created in build.pg.... So apparently nothing is uploaded, but it says compressing files...

Any clues on where I can look for info?

**Comment by andersborgabiro** [comment]
Works great for me, despite the classical error.

    call phonegap remote --no-proxy build android

Yet I got this from phonegap-cli when upgrading npm, node, cordova-cli and phonegap-cli (in that order) today. Windows 10 64-bit.

PS C:\WINDOWS\system32> npm i -g phonegap
C:\Users\Anders Borg\AppData\Roaming\npm\phonegap -> C:\Users\Anders Borg\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"10.15.3","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\phonegap\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ phonegap@9.0.0
added 128 packages from 161 contributors, removed 525 packages, updated 46 packages and moved 67 packages in 24.996s
PS C:\WINDOWS\system32>

**Comment by gRegorLove** [comment]
Same error here.

Environment:
Phonegap 9.0.0
OS: Win10
Node: v10.16.0
npm: 6.9.0

**Comment by RamiAhmed** [comment]
I am seeing this same error as well.

Environment:
```
npm 6.11.3
node v10.17.0
cordova 9.0.0 (cordova-lib@9.0.1)
phonegap 9.0.0
Windows 10
```
Error:

```
[phonegap] uploading the app...
There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:136:11)
    at Object.rmdir (fs.js:671:14)
    at Object.cleanup (C:\Program Files\nodejs\node_modules\npm\node_modules\phonegap\node_modules\phonegap-build\lib\phonegap-build\create\zip.js:119:16)
    at Object.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\phonegap\node_modules\phonegap-build\lib\phonegap-build\build\remote.js:71:21)
    at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\phonegap\node_modules\phonegap-build-api\lib\api.js:230:26)
    at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\phonegap\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\phonegap\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\phonegap\node_modules\request\request.js:1076:12). Have you remembered to unlock the certificate on build.phonegap.com?
```

**Comment by CostaUniud** [comment]
> Works great for me, despite the classical error.
> 
> ```
> call phonegap remote --no-proxy build android
> ```
> 
> Yet I got this from phonegap-cli when upgrading npm, node, cordova-cli and phonegap-cli (in that order) today. Windows 10 64-bit.
> 
> PS C:\WINDOWS\system32> npm i -g phonegap
> C:\Users\Anders Borg\AppData\Roaming\npm\phonegap -> C:\Users\Anders Borg\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js
> npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"10.15.3","npm":"6.13.0"})
> npm WARN notsup Not compatible with your version of node/npm: got@5.7.1
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\phonegap\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> * phonegap@9.0.0
>   added 128 packages from 161 contributors, removed 525 packages, updated 46 packages and moved 67 packages in 24.996s
>   PS C:\WINDOWS\system32>

I try to use this command, but it say not recognize "call". I have update npm, node, cordova and phonegap on Win10.

**Comment by DimosthenisK** [comment]
This still has no fix?

**Comment by andersborgabiro** [comment]
My experience of this, as mentioned before, is that building still always works, so did you check the result at build.phonegap.com?

Of course it's insane that this probably very simple bug is not fixed, but maybe there's only a janitor and his dog that maintains the CLI tools by now (I'm hopefully kidding).

**Comment by DimosthenisK** [comment]
It's been more than 8 months, this is definitely not the support you expect from a company like adobe, especially for a tool that also has a paid plan.

**Comment by dsukhin** [comment]
Based on the stack trace, the issue is actually in the phonegap-build dependency: https://github.com/phonegap/node-phonegap-build/

This issue is the relevant one and it seems there is a quick fix PR: https://github.com/phonegap/node-phonegap-build/issues/68

Since the PR has not been merged (and this issue is largely being ignored) you might also consider downgrading node <v10 when using PBG to get rid of the error.

**Comment by andersborgabiro** [comment]
Updating PhoneGap via npm also indicates it's time to update the CLI applictions (this is after updating npm, node and cordova):

```
PS C:\WINDOWS\system32> npm i -g phonegap
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
C:\Users\red_s\AppData\Roaming\npm\phonegap -> C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\phonegap\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"10.16.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules\phonegap\node_modules\fsevents\node_modules\abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\abbrev' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules\phonegap\node_modules\fsevents\node_modules\ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\ansi-regex' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules\phonegap\node_modules\fsevents\node_modules\aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\aproba' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules\phonegap\node_modules\fsevents\node_modules\balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\balanced-match' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.1.4 (node_modules\phonegap\node_modules\fsevents\node_modules\chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\chownr' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules\phonegap\node_modules\fsevents\node_modules\code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\code-point-at' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules\phonegap\node_modules\fsevents\node_modules\concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\concat-map' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules\phonegap\node_modules\fsevents\node_modules\console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\console-control-strings' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules\phonegap\node_modules\fsevents\node_modules\core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\core-util-is' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules\phonegap\node_modules\fsevents\node_modules\deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\deep-extend' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules\phonegap\node_modules\fsevents\node_modules\delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\delegates' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules\phonegap\node_modules\fsevents\node_modules\detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\detect-libc' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules\phonegap\node_modules\fsevents\node_modules\fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\fs.realpath' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules\phonegap\node_modules\fsevents\node_modules\has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\has-unicode' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules\phonegap\node_modules\fsevents\node_modules\inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\inherits' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules\phonegap\node_modules\fsevents\node_modules\ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\ini' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules\phonegap\node_modules\fsevents\node_modules\isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\isarray' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.5 (node_modules\phonegap\node_modules\fsevents\node_modules\minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\minimist' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@2.1.2 (node_modules\phonegap\node_modules\fsevents\node_modules\ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\ms' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.ms.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm-normalize-package-bin@1.0.1 (node_modules\phonegap\node_modules\fsevents\node_modules\npm-normalize-package-bin):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\npm-normalize-package-bin' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.npm-normalize-package-bin.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules\phonegap\node_modules\fsevents\node_modules\number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\number-is-nan' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules\phonegap\node_modules\fsevents\node_modules\object-assign):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\object-assign' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.object-assign.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-homedir@1.0.2 (node_modules\phonegap\node_modules\fsevents\node_modules\os-homedir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\os-homedir' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.os-homedir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules\phonegap\node_modules\fsevents\node_modules\os-tmpdir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\os-tmpdir' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.os-tmpdir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.1 (node_modules\phonegap\node_modules\fsevents\node_modules\path-is-absolute):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\path-is-absolute' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.path-is-absolute.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@2.0.1 (node_modules\phonegap\node_modules\fsevents\node_modules\process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\process-nextick-args' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.process-nextick-args.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules\phonegap\node_modules\fsevents\node_modules\safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\safe-buffer' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safer-buffer@2.1.2 (node_modules\phonegap\node_modules\fsevents\node_modules\safer-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\safer-buffer' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.safer-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.4 (node_modules\phonegap\node_modules\fsevents\node_modules\sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\sax' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.sax.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.7.1 (node_modules\phonegap\node_modules\fsevents\node_modules\semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\semver' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.semver.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: set-blocking@2.0.0 (node_modules\phonegap\node_modules\fsevents\node_modules\set-blocking):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\set-blocking' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.set-blocking.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: signal-exit@3.0.2 (node_modules\phonegap\node_modules\fsevents\node_modules\signal-exit):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\signal-exit' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.signal-exit.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules\phonegap\node_modules\fsevents\node_modules\strip-json-comments):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\strip-json-comments' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.strip-json-comments.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules\phonegap\node_modules\fsevents\node_modules\util-deprecate):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\util-deprecate' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.util-deprecate.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules\phonegap\node_modules\fsevents\node_modules\wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\wrappy' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules\phonegap\node_modules\fsevents\node_modules\yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\yallist' -> 'C:\Users\red_s\AppData\Roaming\npm\node_modules\phonegap\node_modules\fsevents\node_modules\.yallist.DELETE'

+ phonegap@9.0.0
added 2 packages from 1 contributor and updated 4 packages in 23.012s
```
