### ISSUE TITLE
phonegap create error

### ISSUE THREAD

**Issue by LillyWebsites** [phonegap/phonegap-cli#829]
### PhoneGap CLI, node & npm versions
phonegap -v
9.0.0
node -v
v10.15.0
npm -v
6.4.1

### Expected Behaviour
create  a new project

### Actual Behaviour
unhandled exceptions

### Steps to Reproduce 
phonegap create [path] [id] [name]

#### Error messages
There was an unhandled exception within phonegap-cli! If you would like to help the PhoneGap project, please file the following details over at https://github.com/phonegap/phonegap-cli/issues
SyntaxError: Unexpected token l in JSON at position 0
    at JSON.parse (<anonymous>)
    at CLI.module.exports [as create] (C:\Users\User\AppData\Roaming\npm\node_modules\phonegap\lib\cli\create.js:32:22)
    at CLI.module.exports [as argv] (C:\Users\User\AppData\Roaming\npm\node_modules\phonegap\lib\cli\argv.js:111:17)
    at runPhoneGapCommand (C:\Users\User\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js:46:9)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\phonegap\bin\phonegap.js:38:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by LillyWebsites** [comment]
After updating node and without ID/Name Parameters it worked
